import { fileURLToPath } from 'node:url';

import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import { tanstackRouter } from '@tanstack/router-plugin/vite';
import { defineConfig } from 'vitest/config';

// stack-web.md rules 1-3: React 19 on Vite 8, the router in from the first
// screen with its file-based route tree generated by @tanstack/router-plugin
// (rule 38). Vitest reads this same config so the TSX transform, the path
// aliases and import.meta.env are already correct (rule 41).
// The API's dev port (apps/api/src/config/env.ts PORT default). stack-api.md
// rule 25's fast loop runs Vite and the API as two processes; this is where they
// are stitched back into one origin.
const API_DEV_TARGET = 'http://localhost:3000';

export default defineConfig({
  resolve: {
    // Mirrors tsconfig's `@/*` path — Vite and Vitest do not read tsconfig
    // paths on their own.
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  server: {
    // stack-web.md rule 62: `make dev-all` runs Vite and Nest on two ports, so
    // `lib/api/fetcher.ts`'s relative `/api` and the same-origin `io()` socket
    // would resolve to Vite's own origin and 404. Proxying both here keeps the
    // one-origin invariant (stack-api.md rule 48) true in the loop developers
    // use, with no CORS added to the API. This path list is the second place
    // the API's top-level paths are named.
    proxy: {
      // `/api/*` -> Nest at the root: the `/api` prefix is the proxy's, not a
      // Nest global prefix, so a new `/api/x` route needs no edit here.
      '/api': {
        target: API_DEV_TARGET,
        rewrite: (path) => path.replace(/^\/api/, ''),
      },
      // Socket.IO's default path. `ws: true` for the upgrade; no `changeOrigin`
      // so the browser's real Origin reaches the handshake's allow-list check
      // (stack-api.md rule 38).
      '/socket.io': {
        target: API_DEV_TARGET,
        ws: true,
      },
    },
  },
  plugins: [
    tanstackRouter({
      target: 'react',
      routesDirectory: './src/routes',
      generatedRouteTree: './src/routeTree.gen.ts',
      autoCodeSplitting: true,
      // Keep colocated specs and the `-shell/` chrome out of the route tree.
      routeFileIgnorePattern: '\\.(test|spec)\\.[tj]sx?$',
    }),
    react(),
    tailwindcss(),
  ],
  test: {
    // stack-web.md rule 44: jsdom only where a component or a hook renders. The
    // default is node; a file that renders opts in with
    // `/** @vitest-environment jsdom */` at its top.
    environment: 'node',
    // React Testing Library registers its afterEach(cleanup) against the global
    // hooks, so unmounting between tests needs these exposed.
    globals: true,
    setupFiles: ['./vitest.setup.ts'],
    include: [
      'src/**/*.{test,spec}.{ts,tsx}',
      'scripts/**/*.{test,spec}.ts',
      'test/**/*.spec.{ts,tsx}',
    ],
    // The *.test-d.ts type-level specs are enforced by `tsc --noEmit` (the
    // typecheck script), which fails on an unsatisfied @ts-expect-error — no
    // separate Vitest typecheck pass needed.
  },
});
