import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

const here = dirname(fileURLToPath(import.meta.url));
const webRoot = join(here, '..', '..', '..');
const generated = readFileSync(
  join(here, 'generated', 'tormented-path.ts'),
  'utf8',
);

describe("Orval's generated client", () => {
  // stack-web.md rule 57 / FR.11.3: the client, the hooks and the handlers are
  // generated, not hand-written.
  it('is marked generated and not hand-edited', () => {
    expect(generated).toMatch(/Generated by orval/);
    expect(generated).toMatch(/Do not edit manually/);
  });

  // architecture-web.md rule 11: every generated request goes through the single
  // mutator, never a bare fetch.
  it('routes every request through the fetch mutator', () => {
    expect(generated).toMatch(/import \{\s*fetcher\s*\} from '\.\.\/fetcher/);
    expect(generated).toMatch(/return fetcher</);
    // No direct global fetch in the generated client.
    expect(generated).not.toMatch(/[^.\w]fetch\(/);
  });

  // FR.11.5: regenerating from the committed document reproduces the committed
  // output exactly — nothing under generated/ is dirty after a fresh run.
  it('reproduces the committed output exactly when regenerated', () => {
    execFileSync('pnpm', ['exec', 'orval', '--config', 'orval.config.ts'], {
      cwd: webRoot,
      encoding: 'utf8',
      stdio: 'pipe',
    });
    // `git diff` compares against the committed version and ignores untracked
    // files, so this passes both before the first commit and after.
    let diffFailed = false;
    try {
      execFileSync('git', ['diff', '--exit-code', 'src/lib/api/generated'], {
        cwd: webRoot,
        encoding: 'utf8',
      });
    } catch {
      diffFailed = true;
    }
    expect(diffFailed).toBe(false);
  });
});
