// stack-web.md rule 45: the JSON-path-to-custom-property mapping lives here, in
// the generator. `color.accent.default` becomes `--color-accent` and
// `spacing.5` becomes `--spacing-5`; every other path follows the same shape.
//
// rule 54: `theme.ts` carries the same names with a hex-to-`0x` conversion, so
// the PixiJS renderer reads a number where CSS cannot reach.

export type TokenTree = { [key: string]: string | number | TokenTree };

type Entry = { property: string; value: string };

// Segments that never reach the output.
const SKIP_KEYS = new Set(['$schema', 'note']);

// A trailing `default` segment is dropped: color.accent.default -> --color-accent.
const DROP_TRAILING = 'default';

// Organisational buckets in the color tree — design.md §3 names its tokens `bg`,
// `surface`, `success`, `danger` with no bucket prefix, so these segments are
// dropped from the property name. `accent` and `damageType` are kept: they carry
// token identity (`accent.hover`, `damageType.fire`).
const DROP_COLOR_BUCKETS = new Set(['neutral', 'semantic']);

function kebab(segment: string): string {
  return segment
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2')
    .toLowerCase();
}

// Which `--<prefix>-` a top-level path maps to. The two documented cases —
// `color` and `spacing` — plus the Tailwind v4 namespaces for the rest, so a
// utility class resolves straight to the generated property.
const PREFIXES: Array<{ match: string[]; prefix: string }> = [
  { match: ['color'], prefix: 'color' },
  { match: ['spacing'], prefix: 'spacing' },
  { match: ['radius'], prefix: 'radius' },
  { match: ['size'], prefix: 'size' },
  { match: ['typography', 'fontFamily'], prefix: 'font' },
  { match: ['typography', 'fontWeight'], prefix: 'font-weight' },
  { match: ['typography', 'fontSize'], prefix: 'text' },
  { match: ['typography', 'lineHeight'], prefix: 'leading' },
  { match: ['typography', 'letterSpacing'], prefix: 'tracking' },
  { match: ['motion', 'duration'], prefix: 'duration' },
  { match: ['motion', 'easing'], prefix: 'ease' },
];

function resolvePrefix(
  path: string[],
): { prefix: string; rest: string[] } | null {
  for (const { match, prefix } of PREFIXES) {
    if (
      match.length <= path.length &&
      match.every((segment, index) => path[index] === segment)
    ) {
      return { prefix, rest: path.slice(match.length) };
    }
  }
  return null;
}

/**
 * Flattens the token tree into ordered `--property: value` entries, applying the
 * path-to-property mapping. Order follows a depth-first walk of the source, so
 * the output is stable across runs.
 */
export function flattenTokens(tree: TokenTree): Entry[] {
  const entries: Entry[] = [];

  const walk = (node: TokenTree, path: string[]): void => {
    for (const [key, value] of Object.entries(node)) {
      if (SKIP_KEYS.has(key)) {
        continue;
      }
      const nextPath = [...path, key];
      if (value !== null && typeof value === 'object') {
        walk(value, nextPath);
        continue;
      }

      const resolved = resolvePrefix(nextPath);
      if (!resolved) {
        continue;
      }
      let rest = resolved.rest;
      if (resolved.prefix === 'color') {
        rest = rest.filter((segment) => !DROP_COLOR_BUCKETS.has(segment));
      }
      if (rest.length > 1 && rest.at(-1) === DROP_TRAILING) {
        rest = rest.slice(0, -1);
      }
      const tail = rest.map(kebab).join('-');
      const property = tail
        ? `--${resolved.prefix}-${tail}`
        : `--${resolved.prefix}`;
      entries.push({ property, value: String(value) });
    }
  };

  walk(tree, []);
  return entries;
}

const HEX = /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/;

function hexToInt(hex: string): number {
  const body = hex.slice(1);
  const full =
    body.length === 3
      ? body
          .split('')
          .map((c) => c + c)
          .join('')
      : body;
  return Number.parseInt(full, 16);
}

const CSS_HEADER = [
  '/*',
  ' * GENERATED by scripts/generate-theme.ts from docs/design-tokens.json.',
  ' * Do not edit by hand — stack-web.md rule 45. Run `pnpm --filter @gomide/web',
  ' * generate:theme` after changing the token file.',
  ' */',
].join('\n');

const TS_HEADER = [
  '// GENERATED by scripts/generate-theme.ts from docs/design-tokens.json.',
  '// Do not edit by hand — stack-web.md rules 45 and 54. Run',
  '// `pnpm --filter @gomide/web generate:theme` after changing the token file.',
].join('\n');

export function renderThemeCss(tree: TokenTree): string {
  const entries = flattenTokens(tree);
  const lines = entries.map(
    ({ property, value }) => `  ${property}: ${value};`,
  );
  return `${CSS_HEADER}\n\n@theme {\n${lines.join('\n')}\n}\n`;
}

export function renderThemeTs(tree: TokenTree): string {
  const entries = flattenTokens(tree);
  const themeLines = entries.map(
    ({ property, value }) =>
      `  ${JSON.stringify(property)}: ${JSON.stringify(value)},`,
  );
  const hexLines = entries
    .filter(({ value }) => HEX.test(value))
    .map(
      ({ property, value }) =>
        `  ${JSON.stringify(property)}: 0x${hexToInt(value)
          .toString(16)
          .padStart(6, '0')},`,
    );

  return [
    TS_HEADER,
    '',
    '// Every generated custom property and its string value. The keys match the',
    '// `--*` declarations in theme.css exactly.',
    'export const theme = {',
    ...themeLines,
    '} as const;',
    '',
    '// The subset that is a plain hex colour, as a 0x integer for PixiJS text',
    '// styles (stack-web.md rule 54).',
    'export const themeColorHex = {',
    ...hexLines,
    '} as const;',
    '',
    'export type ThemeProperty = keyof typeof theme;',
    '',
  ].join('\n');
}
