import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { getAuthTables } from 'better-auth/db';

import { authSharedOptions } from '../src/modules/auth/infrastructure/auth.options.js';

// `make api-auth-schema` (auth.md rule 5): write `user`, `session`, `account`
// and `verification` into the auth module's Drizzle schema and commit the file
// unedited.
//
// auth.md's Commands table names `better-auth generate`, the `@better-auth/cli`
// command. That package tops out at 1.5.0-beta and its `account` table is
// missing the `issuer` column and the `(issuer, accountId)` unique index that
// `better-auth` 1.7.2 (stack-api.md rules 26-28) validates at adapter init — a
// CLI-generated schema makes every `auth.api` call throw. So this script emits
// the schema from `better-auth`'s own `getAuthTables`, the exact metadata the
// runtime adapter checks against: the file cannot drift from the library
// because it is derived from the library. Output is deterministic, so
// regeneration stays byte-identical and `make check`'s drift guard holds.
//
// AUTH_SCHEMA_OUT lets the drift spec generate to a throwaway path (mirrors
// OPENAPI_OUT in generate-openapi.ts).

type FieldType = 'string' | 'number' | 'boolean' | 'date';

type FieldDef = {
  type: FieldType | `${FieldType}[]`;
  fieldName?: string;
  required?: boolean;
  unique?: boolean;
  defaultValue?: unknown;
  onUpdate?: unknown;
  index?: boolean;
  references?: { model: string; field: string; onDelete?: string };
};

type TableDef = {
  modelName: string;
  order?: number;
  fields: Record<string, FieldDef>;
  indexes?: Array<{ fields: string[]; unique?: boolean }>;
};

const COLUMN_FN: Record<FieldType, string> = {
  string: 'text',
  number: 'integer',
  boolean: 'boolean',
  date: 'timestamp',
};

const toSnakeCase = (value: string): string =>
  value.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);

function renderColumn(key: string, field: FieldDef): string {
  const baseType = field.type.replace('[]', '') as FieldType;
  const columnName = toSnakeCase(field.fieldName ?? key);
  const parts = [`${COLUMN_FN[baseType]}('${columnName}')`];

  if (field.references) {
    const onDelete = field.references.onDelete
      ? `, { onDelete: '${field.references.onDelete}' }`
      : '';
    parts.push(
      `.references(() => ${field.references.model}.${field.references.field}${onDelete})`,
    );
  }
  if (field.defaultValue !== undefined) {
    parts.push(
      baseType === 'date'
        ? '.defaultNow()'
        : `.default(${JSON.stringify(field.defaultValue)})`,
    );
  }
  if (field.onUpdate !== undefined) parts.push('.$onUpdate(() => new Date())');
  if (field.unique) parts.push('.unique()');
  if (field.required) parts.push('.notNull()');

  return `  ${key}: ${parts.join('')},`;
}

function renderTable(table: TableDef): string {
  const lines = [`export const ${table.modelName} = pgTable(`];
  lines.push(`  '${table.modelName}',`);
  lines.push('  {');
  lines.push(`    id: text('id').primaryKey(),`);
  for (const [key, field] of Object.entries(table.fields)) {
    lines.push(`  ${renderColumn(key, field)}`);
  }
  lines.push('  },');

  const indexRows: string[] = [];
  for (const [key, field] of Object.entries(table.fields)) {
    if (field.index) {
      indexRows.push(
        `    index('${table.modelName}_${key}_idx').on(table.${key}),`,
      );
    }
  }
  for (const composite of table.indexes ?? []) {
    const columns = composite.fields.map((name) => `table.${name}`).join(', ');
    const name = `${table.modelName}_${composite.fields.join('_')}_idx`;
    const fn = composite.unique ? 'uniqueIndex' : 'index';
    indexRows.push(`    ${fn}('${name}').on(${columns}),`);
  }
  if (indexRows.length > 0) {
    lines.push('  (table) => [');
    lines.push(...indexRows);
    lines.push('  ],');
  }

  lines.push(');');
  return lines.join('\n');
}

const tables = Object.values(
  getAuthTables(authSharedOptions) as Record<string, TableDef>,
).sort((a, b) => (a.order ?? 0) - (b.order ?? 0));

const body = tables.map(renderTable).join('\n\n');
const file = `// Generated by \`make api-auth-schema\` from Better Auth's own table
// metadata (auth.md rule 5). Do not edit by hand — every change is reverted on
// the next run and CI drift-checks it.
import {
  boolean,
  index,
  integer,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from 'drizzle-orm/pg-core';

${body}
`;

const apiRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const outFile =
  process.env.AUTH_SCHEMA_OUT ??
  join(
    apiRoot,
    'src/modules/auth/infrastructure/database/schema/auth.schema.ts',
  );

writeFileSync(outFile, file);
process.stdout.write(`wrote ${outFile}\n`);
